### ISSUE TITLE
Improve XML parser error message for missing attribute

### ISSUE THREAD

**Issue by William-Rohm** [OfficeDev/Interop-MailSim#11]
1. Create a myOperations.xml file, leaving out the Count attribute from a SendMail element.

2. The following error message is generated -- note that it names the missing attribute, but not the enclosing element itself, which makes it hard to debug

7/16/2015 2:47:58 PM Error      : XML Processing        : myOperations.xml schem

a validation exception encountered

System.Xml.Schema.XmlSchemaValidationException: The required attribute 'Count' i

s missing.

   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidati

onException e, XmlSeverityType severity)

   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, Stri

ng arg)

   at System.Xml.Schema.XmlSchemaValidator.CheckRequiredAttributes(SchemaElement

Decl currentElementDecl)

   at System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes(XmlSchemaInfo

schemaInfo)

   at System.Xml.XsdValidatingReader.ProcessElementEvent()

   at System.Xml.XsdValidatingReader.ProcessReaderEvent()

   at System.Xml.XsdValidatingReader.Read()

   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)

   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)

   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean prese

rveWhitespace)

   at System.Xml.XmlDocument.Load(XmlReader reader)

   at MailSim.ConfigurationFile.ValidateXML(String xmlFile, String xmlSchema)

7/16/2015 2:47:58 PM Error      : XML Processing        : Unable to process the

operation file myOperations.xml

**Comment by PuiL-Msft** [comment]
This is a limitation of the .net library.
