### ISSUE TITLE
MailSend error -- "Unable to get users from GAL to select random users"

### ISSUE THREAD

**Issue by William-Rohm** [OfficeDev/Interop-MailSim#26]
[1] With one recipient specified, MailSend works as expected.
[2] With RandomRecipients specified, with or without an explicit DistributionList, MailSend returns the above error message and skips mail sending.  The complete message is:
```
<Error Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Unable to get users from GAL to select random users
System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/proptag/0x3D150102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at MailSim.ProvidersOM.MailStoreProviderOM.GetGlobalAddressList()
   at MailSim.ExecuteSequence.GetRecipients(String name, RecipientTypes[] type, Object[] recipientObject)</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Recipient is not specified, skipping the operation</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Failed to run task</Detail>
</Error>
```
[3] Here is the GAL from my Outlook client:
![gal](https://cloud.githubusercontent.com/assets/13560879/9363696/be63dcf4-465c-11e5-825e-68eb9b25a01d.gif)

**Comment by William-Rohm** [comment]
Sequence file:
```
<?xml version="1.0" encoding="utf-8"?>

<MailSimSequence 
    LogFileLocation="C:\MailSimDemo\Logs\">

  <OperationGroup Name="MailSend vs GAL" 
      OperationFile="MailSendGALOps.xml"
      Iterations="1">

    <Task Name="OpMailSend" Iterations="2" Sleep="1"/>

  </OperationGroup>

</MailSimSequence>
```

Operations file:

```
<?xml version="1.0" encoding="utf-8"?>

<MailSimOperations>

  <MailSend OperationName="OpMailSend" Sleep="3">

<!--
    <RandomRecipients DistributionList="Test Accounts 0-9 DL">1</RandomRecipients>
    <RandomRecipients DistributionList="testaccts0-9">1</RandomRecipients>  <!-- this is log "2015-08-19 10-15-44..." -->
    <Recipients>TestAcct41</Recipients>  <!-- this is log "2015-08-19 10-01-45..." -->
-->
    <RandomRecipients DistributionList="">1</RandomRecipients> <!-- this is log "2015-08-19 10-12-30..." -->
    <Subject>Hello from the MailSim Demo</Subject>
  </MailSend>

</MailSimOperations>
```

**Comment by William-Rohm** [comment]
Log file for one specified Recipient (2015-08-19 10-01-45):

```
<MailSim>
<Info Name="DefaultInboxMonitor" Time="8/19/2015 10:01:45 AM">
  <Detail>Registered event to \\williamtest@exhr-3651dom.extest.microsoft.com\Inbox</Detail>
</Info>
<Info Name="MailSend vs GAL" Time="8/19/2015 10:01:45 AM">
  <Detail>Starting group run 1</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:45 AM">
  <Detail>Running task 1</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:45 AM">
  <Detail>Subject: 8/19/2015 10:01:45 AM - Hello from the MailSim Demo</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:45 AM">
  <Detail>Body: 8/19/2015 10:01:45 AM - 
Default Body 
</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:45 AM">
  <Detail>Recipient: TestAcct41</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:45 AM">
  <Detail>Sleeping for 3 seconds</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:48 AM">
  <Detail>Completed task run 1</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:48 AM">
  <Detail>Sleeping for 1 seconds</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:49 AM">
  <Detail>Running task 2</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:49 AM">
  <Detail>Subject: 8/19/2015 10:01:49 AM - Hello from the MailSim Demo</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:49 AM">
  <Detail>Body: 8/19/2015 10:01:49 AM - 
Default Body 
</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:49 AM">
  <Detail>Recipient: TestAcct41</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:49 AM">
  <Detail>Sleeping for 3 seconds</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:52 AM">
  <Detail>Completed task run 2</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:01:52 AM">
  <Detail>Sleeping for 1 seconds</Detail>
</Info>
<Info Name="MailSend vs GAL" Time="8/19/2015 10:01:53 AM">
  <Detail>Completed group task run 1</Detail>
</Info>
<Info Name="DefaultInboxMonitor" Time="8/19/2015 10:01:53 AM">
  <Detail>Unregistered event to \\williamtest@exhr-3651dom.extest.microsoft.com\Inbox</Detail>
</Info>
</MailSim>
```

**Comment by William-Rohm** [comment]
Log file for empty DL (2015-08-19 10-12-30):
```
<MailSim>
<Info Name="DefaultInboxMonitor" Time="8/19/2015 10:12:30 AM">
  <Detail>Registered event to \\williamtest@exhr-3651dom.extest.microsoft.com\Inbox</Detail>
</Info>
<Info Name="MailSend vs GAL" Time="8/19/2015 10:12:30 AM">
  <Detail>Starting group run 1</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Running task 1</Detail>
</Info>
<Error Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Unable to get users from GAL to select random users
System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/proptag/0x3D150102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at MailSim.ProvidersOM.MailStoreProviderOM.GetGlobalAddressList()
   at MailSim.ExecuteSequence.GetRecipients(String name, RecipientTypes[] type, Object[] recipientObject)</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Recipient is not specified, skipping the operation</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Failed to run task</Detail>
</Error>
<Info Name="OpMailSend" Time="8/19/2015 10:12:30 AM">
  <Detail>Sleeping for 1 seconds</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:12:31 AM">
  <Detail>Running task 2</Detail>
</Info>
<Error Name="OpMailSend" Time="8/19/2015 10:12:31 AM">
  <Detail>Unable to get users from GAL to select random users
System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/proptag/0x3D150102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at MailSim.ProvidersOM.MailStoreProviderOM.GetGlobalAddressList()
   at MailSim.ExecuteSequence.GetRecipients(String name, RecipientTypes[] type, Object[] recipientObject)</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:12:31 AM">
  <Detail>Recipient is not specified, skipping the operation</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:12:31 AM">
  <Detail>Failed to run task</Detail>
</Error>
<Info Name="OpMailSend" Time="8/19/2015 10:12:31 AM">
  <Detail>Sleeping for 1 seconds</Detail>
</Info>
<Info Name="MailSend vs GAL" Time="8/19/2015 10:12:32 AM">
  <Detail>Completed group task run 1</Detail>
</Info>
<Info Name="DefaultInboxMonitor" Time="8/19/2015 10:12:32 AM">
  <Detail>Unregistered event to \\williamtest@exhr-3651dom.extest.microsoft.com\Inbox</Detail>
</Info>
</MailSim>
```

**Comment by William-Rohm** [comment]
Log file for DL "testaccts0-9" (2015-08-19 10-15-44):
```
<MailSim>
<Info Name="DefaultInboxMonitor" Time="8/19/2015 10:15:44 AM">
  <Detail>Registered event to \\williamtest@exhr-3651dom.extest.microsoft.com\Inbox</Detail>
</Info>
<Info Name="MailSend vs GAL" Time="8/19/2015 10:15:44 AM">
  <Detail>Starting group run 1</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:15:44 AM">
  <Detail>Running task 1</Detail>
</Info>
<Error Name="OpMailSend" Time="8/19/2015 10:15:44 AM">
  <Detail>Unable to get users from GAL to select random users
System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/proptag/0x3D150102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at MailSim.ProvidersOM.MailStoreProviderOM.GetGlobalAddressList()
   at MailSim.ExecuteSequence.GetRecipients(String name, RecipientTypes[] type, Object[] recipientObject)</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:15:44 AM">
  <Detail>Recipient is not specified, skipping the operation</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:15:44 AM">
  <Detail>Failed to run task</Detail>
</Error>
<Info Name="OpMailSend" Time="8/19/2015 10:15:44 AM">
  <Detail>Sleeping for 1 seconds</Detail>
</Info>
<Info Name="OpMailSend" Time="8/19/2015 10:15:45 AM">
  <Detail>Running task 2</Detail>
</Info>
<Error Name="OpMailSend" Time="8/19/2015 10:15:45 AM">
  <Detail>Unable to get users from GAL to select random users
System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/proptag/0x3D150102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at MailSim.ProvidersOM.MailStoreProviderOM.GetGlobalAddressList()
   at MailSim.ExecuteSequence.GetRecipients(String name, RecipientTypes[] type, Object[] recipientObject)</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:15:45 AM">
  <Detail>Recipient is not specified, skipping the operation</Detail>
</Error>
<Error Name="OpMailSend" Time="8/19/2015 10:15:45 AM">
  <Detail>Failed to run task</Detail>
</Error>
<Info Name="OpMailSend" Time="8/19/2015 10:15:45 AM">
  <Detail>Sleeping for 1 seconds</Detail>
</Info>
<Info Name="MailSend vs GAL" Time="8/19/2015 10:15:46 AM">
  <Detail>Completed group task run 1</Detail>
</Info>
<Info Name="DefaultInboxMonitor" Time="8/19/2015 10:15:46 AM">
  <Detail>Unregistered event to \\williamtest@exhr-3651dom.extest.microsoft.com\Inbox</Detail>
</Info>
</MailSim>
```
